# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build: 
    runs-on: ubuntu-latest 
    name: Build Azure Sphere Apps 

    steps: 
    - name: Checkout 
      uses: actions/checkout@v2 

    - name: Build image for azsphere builds and Start container from build image 
      run: | 
        docker build --target build -t hlbuildimage -f Samples/HelloWorld/HelloWorld_HighLevelApp/.devcontainer/Dockerfile . 
        docker run --name hlbuildcontainer hlbuildimage 

    - name: Copy container build output 
      run: 
        docker cp hlbuildcontainer:/build HLOutput 

    - name: Publish HL imagepackage 
      uses: actions/upload-artifact@v2 
      with: 
        name: HL imagepackage 
        path: ${{ github.workspace }}/HLOutput/HelloWorld_HighLevelApp.imagepackage 

